### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by ianchen0119** [ianchen0119/AwesomeCS#1]
## CH0

- [x] Main page

## CH1

- [x] 一此搞懂 ISA、CISC 與 RISC
- [x] 數值系統與補數
- [x] 關於計算機，你必須知道的事 -- CPU 快取
- [x] 透過數位邏輯電路學習 Bitwise 操作
- [x] 透過 RISC-V 模擬器搞懂指令管線化
- [x] 淺談分支預測與 Hazards 議題
- [x] IEEE-754 與浮點數運算
- [x] 彙編器與連結器(上)
- [x] 彙編器與連結器(下)

## CH2

- [x] RISC-V::RV32I 指令介紹
- [x] RISC-V::關於基本暫存器
- [x] RISC-V::中斷與異常處理 -- 異常篇
- [x] RISC-V::中斷與異常處理 -- 中斷篇
- [x] RISC-V::中斷與異常處理 -- PLIC 介紹
- [x] 窺探 ISA 的精妙設計 (X)

## CH3

- [x] GNU Debugger
- [x] GNU Compiler Collection
- [ ] Valgrind (X)
- [x] Git
- [x] Makefile
- [x] Vim (X)
- [x] 善用 Linux Programmer's Manual
- [x] 那些多人混戰的開發經驗談 (X)

## CH4

- [x] 教練，我想自幹作業系統!
- [x] UNIX、BSD 與 Linux 的愛恨情仇
- [x] 作業系統:: Hello, OS!
- [x] 作業系統::中斷與異常
- [x] 作業系統::學習內文交換
- [x] 作業系統::關於任務排程
- [x] 作業系統:: Shell
- [x] 作業系統::淺談檔案系統
- [x] 作業系統::軟體與硬體的距離
- [x] 作業系統:: Microkernel
- [x] 作業系統::淺談特權模式與模式切換
- [x] 作業系統::動態記憶體分配

## CH5

- [x] PPT in Operating system
- [x] POSIX Thread
- [x] 並行程式的潛在問題(一)
- [x] 並行程式的潛在問題(二)
- [x] 並行程式的潛在問題(三)
- [ ] 並行程式的潛在問題(四)  (X)
